// ============================================================
//  PrivacyPolicyScreen.js — in-app mirror of vaultchat.co/android-privacy.html
//
//  Source of truth is the Lovable-hosted page at
//    https://vaultchat.co/android-privacy.html
//  This screen MUST stay in sync with that page so reviewers (Apple
//  App Review + Google Play) see consistent disclosure on either
//  surface. Last sync: 2026-05-02 (v2 — full 14-section policy with
//  per-permission justifications, third-party-services expansion,
//  Children's Privacy, Changes-to-Policy).
// ============================================================

import React from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Linking } from 'react-native';
import { useTheme } from '../services/theme';

export default function PrivacyPolicyScreen({ navigation }) {
  const { bg, card, tx, sub, border, accent } = useTheme();

  const Section = ({ title, children }) => (
    <View style={[s.section, { backgroundColor: card, borderColor: border }]}>
      <Text style={[s.sectionTitle, { color: accent }]}>{title}</Text>
      <Text style={[s.sectionText, { color: tx }]}>{children}</Text>
    </View>
  );

  return (
    <View style={[s.container, { backgroundColor: bg }]}>
      <View style={[s.header, { backgroundColor: card, borderBottomColor: border }]}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={{ color: accent, fontSize: 16 }}>‹ Back</Text>
        </TouchableOpacity>
        <Text style={[s.headerTitle, { color: tx }]}>Privacy Policy</Text>
        <View style={{ width: 50 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 60 }}>
        <View style={s.heroBox}>
          <Text style={s.heroIcon}>🔒</Text>
          <Text style={[s.heroTitle, { color: accent }]}>VaultChat Privacy Policy</Text>
          <Text style={[s.heroSub, { color: sub }]}>
            Last Updated: May 2, 2026
          </Text>
        </View>

        <Section title="Our Commitment">
          VaultChat is an end-to-end encrypted messaging app. We designed it on a simple principle: we should never be able to read your messages. This policy explains what limited information we do collect to keep the service running, how we use it, and the choices you have.
        </Section>

        <Section title="1. Information We Collect">
          Information you provide:{'\n\n'}
          {'  '}• Phone number — required to create an account. Used for SMS verification and to let other users find you when they have your number.{'\n'}
          {'  '}• Display name and @handle — what other users see.{'\n'}
          {'  '}• Optional profile information — email, status message, profile photo if you add them.{'\n'}
          {'  '}• Contact list (optional) — if you grant permission, we check your contacts on-device against our directory. We do NOT upload your full contact list.{'\n\n'}
          Information generated by your use of the service:{'\n\n'}
          {'  '}• Public encryption keys — your device generates a public/private keypair. The public key is published so others can encrypt to you. The private key never leaves your device.{'\n'}
          {'  '}• Encrypted message ciphertext — we briefly store encrypted blobs to deliver them. We cannot read them.{'\n'}
          {'  '}• Push notification tokens — APNs (iOS) and FCM (Android) tokens to deliver call alerts and message notifications.{'\n'}
          {'  '}• Minimal call signaling metadata — to set up the WebRTC handshake. Calls themselves are end-to-end encrypted.{'\n'}
          {'  '}• Account activity — sign-in timestamps and device info, used only for security alerts and stale-session expiry.{'\n\n'}
          We do NOT collect:{'\n\n'}
          {'  '}• Message contents, call audio, or call video — end-to-end encrypted, unreadable to us.{'\n'}
          {'  '}• Advertising identifiers — VaultChat contains no ads or ad SDKs.{'\n'}
          {'  '}• Analytics or behavioral tracking that profiles or sells your data.{'\n'}
          {'  '}• Web-tracking data — VaultChat is not a browser.
        </Section>

        <Section title="2. How We Use Information">
          We use the limited information we collect to:{'\n\n'}
          {'  '}• Create your account and verify your phone number.{'\n'}
          {'  '}• Route encrypted messages and call invites.{'\n'}
          {'  '}• Deliver push notifications so calls ring on your device.{'\n'}
          {'  '}• Help you discover other VaultChat users in your contacts.{'\n'}
          {'  '}• Diagnose service problems and detect abuse.{'\n'}
          {'  '}• Comply with legal obligations.{'\n\n'}
          We do not sell your personal information, and we do not use it to serve advertising.
        </Section>

        <Section title="3. End-to-End Encryption">
          One-to-one messages, voice calls, and video calls between two VaultChat users are protected by end-to-end encryption (E2E). We use the Double Ratchet protocol with X25519 key agreement and XSalsa20-Poly1305 authenticated encryption (via tweetnacl). Only the participating devices hold the keys needed to decrypt the content. Our servers see only ciphertext.{'\n\n'}
          Some auxiliary data is not end-to-end encrypted by design and is necessary for the service to function: your public encryption key, the fact that two accounts have a conversation together and the time of the most recent message, and push notification metadata required to wake your device for incoming messages or calls.
        </Section>

        <Section title="4. When We Share Information">
          Legal and safety:{'\n\n'}
          {'  '}• We may disclose limited account information in response to a valid legal request from a government authority. We push back on overly broad requests.{'\n'}
          {'  '}• We comply with our reporting obligations to the National Center for Missing & Exploited Children (NCMEC) under 18 U.S.C. § 2258A. Because messages are end-to-end encrypted, we do not scan message content; reports are based on user-submitted abuse reports and account-level signals.{'\n'}
          {'  '}• We may share information if necessary to prevent imminent harm, fraud, or illegal activity.{'\n\n'}
          Business transfers: If VaultChat is involved in a merger, acquisition, or sale of assets, your information may be transferred. We will notify you and offer choices before any information becomes subject to a different privacy policy.
        </Section>

        <Section title="5. Your Rights and Choices">
          {'  '}• Access and correction — you can view and edit your profile from inside the app at any time.{'\n'}
          {'  '}• Deletion — you can delete your account from within Settings. Account deletion is irreversible.{'\n'}
          {'  '}• Export — you can request a copy of the limited information associated with your account by emailing the address in §13.{'\n'}
          {'  '}• California, EU, UK residents — you may have additional rights under the CCPA, GDPR, or comparable laws (right to know, deletion, objection to processing). Contact us to exercise these rights.{'\n'}
          {'  '}• Notification controls — you can disable notifications, including incoming-call alerts, in your device's system settings or VaultChat's in-app settings.
        </Section>

        <Section title="6. Data Storage & Retention">
          {'  '}• Message Content (on-device): Decrypted message text is stored only on your device and kept in a local cache for up to 90 days so you can read past conversations offline. Older entries are automatically pruned.{'\n'}
          {'  '}• Encrypted Server Backup (optional, default-on): When enabled, your last 90 days of messages are encrypted on your device using a key derived from your Vault PIN, then uploaded to our backend so you can restore them after reinstalling or signing in on a new device. We never see the contents — without your Vault PIN, the backup is unreadable to us.{'\n'}
          {'  '}• Backend Infrastructure: Encrypted message metadata, account records, push tokens, and encrypted backups are stored in a PostgreSQL database hosted by Supabase, Inc. (US). Our application server is hosted by Railway Corp. (US). Both providers are contractually bound to process this data only on our instructions.{'\n'}
          {'  '}• Server Logs: Retained for 30 days for security and abuse prevention only.{'\n'}
          {'  '}• Account Data: Retained until you delete your account.
        </Section>

        <Section title="7. Third-Party Services">
          VaultChat uses the following service providers to deliver the app. None of them have access to your message content.{'\n\n'}
          {'  '}• Supabase, Inc. — Database and authentication infrastructure. Stores encrypted message metadata, account records, and the encrypted history backup described in Section 6.{'\n'}
          {'  '}• Railway Corp. — Hosting for our application server, which handles real-time message routing and push delivery.{'\n'}
          {'  '}• Twilio Inc. — SMS for account verification codes and security alerts only. Twilio does not have access to your messages.{'\n'}
          {'  '}• Apple Inc. (APNs / App Store) — Push notification delivery on iOS and processing of in-app subscription purchases. Notification payloads never include message content.{'\n'}
          {'  '}• Google LLC (Firebase Cloud Messaging / Google Play Billing) — Push notification delivery on Android via FCM and processing of in-app subscription purchases via Play Billing. Notification payloads never include message content.{'\n'}
          {'  '}• Giphy, Inc. — Optional GIF picker. When you open the GIF picker, your search query (not your messages) is sent to Giphy to return results.{'\n'}
          {'  '}• Sentry (Functional Software, Inc.) — Crash and error reporting. When the app crashes we send anonymized diagnostic data (device model, OS version, stack trace, app version) to help us fix bugs. No message content, contact list, or media is included.{'\n\n'}
          We do not use any advertising networks or analytics trackers that profile or sell your data.
        </Section>

        <Section title="8. Account Deletion">
          You can delete your account at any time:{'\n\n'}
          {'  '}• In-app: open Settings → scroll to Delete Account. The deletion completes immediately and removes your profile, @handle, encryption keys, encrypted server backup, folders, chat preferences, block list, cached contacts, and your authentication record.{'\n'}
          {'  '}• Web (no install required): visit{' '}
          <Text style={[s.link, { color: accent }]} onPress={() => Linking.openURL('https://vaultchat.co/delete-account')}>
            vaultchat.co/delete-account
          </Text>
          {' '}and submit the form. We confirm and complete the deletion within 30 days.{'\n\n'}
          What stays after deletion:{'\n'}
          {'  '}• Messages you sent to other people remain on their devices — that's how end-to-end encryption works; we cannot reach into someone else's phone to delete a message we never had access to.{'\n'}
          {'  '}• Anonymized aggregate metrics (e.g. "5,000 active users last week") that don't identify you personally.{'\n'}
          {'  '}• Records we're legally required to keep — for example, safety reports filed under federal child-protection law (NCMEC reports). These are retained for the period required by law and no longer.{'\n\n'}
          SMS Opt-Out: You can cancel the SMS service at any time by texting "STOP" to our number. Text "HELP" for assistance, or contact{' '}
          <Text style={[s.link, { color: accent }]} onPress={() => Linking.openURL('mailto:privacy@vaultchat.co')}>
            privacy@vaultchat.co
          </Text>.
        </Section>

        <Section title="9. Security">
          We use industry-standard cryptographic protocols (X25519 key agreement, XSalsa20-Poly1305 authenticated encryption, Double Ratchet) to protect message content end-to-end. Server-stored data is encrypted at rest and accessed only by authorized personnel. Face ID and Touch ID authentication is processed entirely on your device by Apple's Secure Enclave; VaultChat never receives, stores, or transmits your biometric data. No system can guarantee perfect security; if you suspect your account has been compromised, contact us immediately.
        </Section>

        <Section title="10. International Users">
          VaultChat is operated from the United States. If you use VaultChat from outside the United States, your information will be transferred to and processed in the United States. By using VaultChat, you consent to that transfer. We rely on appropriate safeguards for transfers from the European Economic Area, United Kingdom, and Switzerland, including standard contractual clauses where required.
        </Section>

        <Section title="11. Children's Privacy">
          VaultChat is intended for users 13 years of age and older. We do not knowingly collect personal information from children under 13. If you believe a child under 13 has provided us with personal information, please contact{' '}
          <Text style={[s.link, { color: accent }]} onPress={() => Linking.openURL('mailto:privacy@vaultchat.co')}>
            privacy@vaultchat.co
          </Text>
          {' '}and we will delete the account and any associated data.
        </Section>

        <Section title="12. Changes to This Policy">
          We may update this Privacy Policy as VaultChat evolves. When we make material changes, we will update the "Last Updated" date at the top of this page and surface an in-app notice the next time you open the app. Continued use of VaultChat after a material update constitutes acceptance of the revised policy.
        </Section>

        <Section title="13. Device Permissions We Request">
          VaultChat asks for the following device permissions. Each is requested only when you use the feature that needs it, and you can revoke any permission at any time from your device's system settings.{'\n\n'}
          {'  '}• Camera — to capture photos and videos for chats and to scan QR codes when adding contacts. Used only when you tap the camera button or open the QR scanner.{'\n'}
          {'  '}• Microphone — to capture audio for voice and video calls and for voice messages. Used only during an active call or voice recording.{'\n'}
          {'  '}• Contacts — to find people you already know who use VaultChat. Your contacts are matched on-device against our directory; we never upload your full address book.{'\n'}
          {'  '}• Notifications — to deliver incoming call alerts and message notifications. Notification content is generic ("New message"); the actual message text is decrypted only after you open the app.{'\n'}
          {'  '}• Photos / Media — to share photos, videos, audio, and documents in chats. Access is granted only to files you explicitly select.{'\n'}
          {'  '}• Location (optional) — only when you tap "Share Location" in a chat. Location is never tracked in the background.{'\n'}
          {'  '}• Face ID / Biometric — to unlock locked chats and the Vault. Biometric data is processed entirely on your device by the OS Secure Enclave; VaultChat never receives or stores it.{'\n'}
          {'  '}• Bluetooth — to route in-call audio to paired Bluetooth headsets during voice and video calls.{'\n'}
          {'  '}• Phone state (Android only) — to bridge incoming VaultChat calls into the Android telecom stack so they appear like normal calls on the lock screen.
        </Section>

        <Section title="14. Contact Us">
          Questions, requests, or concerns about this policy or your information:{'\n\n'}
          AUXXILUS MEDIA LLC{'\n'}
          11 Hetton Ct{'\n'}
          Glassboro, NJ 08028-2903{'\n'}
          United States{'\n\n'}
          Email:{' '}
          <Text style={[s.link, { color: accent }]} onPress={() => Linking.openURL('mailto:privacy@vaultchat.co')}>
            privacy@vaultchat.co
          </Text>{'\n'}
          Website:{' '}
          <Text style={[s.link, { color: accent }]} onPress={() => Linking.openURL('https://vaultchat.co')}>
            vaultchat.co
          </Text>
        </Section>

        <View style={[s.footer, { borderColor: border }]}>
          <Text style={[s.footerText, { color: sub }]}>🔒 VaultChat — Your conversations, your privacy.</Text>
          <Text style={[s.footerText, { color: sub }]}>Built with Signal Protocol encryption.</Text>
        </View>
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  container:    { flex: 1 },
  header:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingTop: 56, paddingBottom: 14, borderBottomWidth: 1 },
  headerTitle:  { fontSize: 16, fontWeight: 'bold' },
  heroBox:      { alignItems: 'center', padding: 24, marginBottom: 8 },
  heroIcon:     { fontSize: 48, marginBottom: 12 },
  heroTitle:    { fontSize: 22, fontWeight: 'bold', textAlign: 'center', marginBottom: 8 },
  heroSub:      { fontSize: 13, textAlign: 'center', lineHeight: 20 },
  section:      { borderRadius: 16, borderWidth: 1, padding: 16, marginBottom: 12 },
  sectionTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 10 },
  sectionText:  { fontSize: 14, lineHeight: 22 },
  link:         { textDecorationLine: 'underline', fontWeight: '600' },
  footer:       { borderTopWidth: 1, paddingTop: 20, marginTop: 8, alignItems: 'center', gap: 6 },
  footerText:   { fontSize: 13, textAlign: 'center' },
});
